apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-search-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mall-search
  template:
    metadata:
      labels:
        app: mall-search
    spec:
      containers:
        - name: mall-search
          image: zaynzzy/all-search:latest # Replace with your Docker image name and tag
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: mall-search-service
spec:
  selector:
    app: mall-search
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer

